### ISSUE TITLE
Using Avrotize with correct Protobuf root location

### ISSUE THREAD

**Issue by edmondop** [clemensv/avrotize#9]
When using `buf`, a largely adopted toolchain for Protobuf today, one defines several modules with a root location

```yaml
modules:
  # Each module entry defines a path, which must be relative to the directory where the
  # buf.yaml is located. You can also specify directories to exclude from a module.
  - path: proto/foo

```

If a file is `proto/foo/bar/bizz.proto` and needs to import `proto/foo/bar/fuzz.proto` it needs to qualify the import like so:

`import "bar/fuzz.proto"`

this syntax however is not handled correctly by avrotize because of this https://github.com/clemensv/avrotize/blob/master/avrotize/prototoavro.py#L129
